# Generated by Django 5.1.6 on 2025-02-20 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='otp',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
