# Generated by Django 5.1.6 on 2025-03-29 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_emailverification_otp_emailverification_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGE', 'Password Change'), ('PAGE_VIEW', 'Page View'), ('CONTACT', 'Contact Form'), ('UPLOAD', 'Upload'), ('COMPRESSION', 'Compression'), ('DOWNLOAD', 'Download'), ('ERROR', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
